# Generated by Django 4.2.3 on 2023-07-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(default='albums/images/default.png', upload_to='albums/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(default='', upload_to='songs/audio/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.album')),
            ],
        ),
    ]
